# -*- coding: utf-8 -*-
"""LambdaOneParameter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlQ5V9vfXg8nhcwIw6bKJblnh7d2388x
"""

# Number squared
def square(num):
   return num**2

square(3)

# With Lambda
lambda num: num**2

square = lambda num: num**2

square(3)